Repository Mohitkumar6122/Code-dump, pull requests merged in 2021-10, with the labels that each got.

#31 Create c++ code to run
  c++ code to run
Labels: hacktoberfest, hacktoberfest-accepted

#32 Create khann's talgo
  khann's talgo
Labels: hacktoberfest, hacktoberfest-accepted

#34 Create heavy_light_decompositon.cpp
  range_queries/heavy_light_decompositon.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#35 Create segTree.cpp
  range_queries/segTree.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#37 Create sparse_table.cpp
  range_queries/sparse_table.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#38 Create mo.cpp
  range_queries/mo.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#39 Added Backtracking
  backtracking/n_queens_all_solution_optimised.cpp
Labels: enhancement, good first issue, question, hacktoberfest, hacktoberfest-accepted

#40 Create ratMaze.cpp
  backtracking/ratMaze.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#41 Create subarray_Sum.cpp
  backtracking/subarray_Sum.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#42 Create sudokusolver.cpp
  backtracking/sudokusolver.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#43 Create n_queens.cpp
  backtracking/n_queens.cpp
Labels: duplicate, invalid

#44 Local
  Housing.csv
  Other/Bubble_sort.cpp
  Other/Coin change DP.py
  Other/Column_Transposition_Cipher.py
  Other/Fractional_knapsack.cpp
  Other/Gfg_dates.java
  Other/Rail_Fence.cpp
  Other/basic_string.py
  Other/bin.java
  Other/fenwick_tree.cpp
  Other/future closest date.java
  Other/gcd.cpp
  Other/mono_alphabetic_ciphers.py
  Other/pigeon_sort.py
  Other/yoo.java
  happens-to-be-the-core-code-for-important-algo-used-in
  khann's algo.cpp
  min_nodes.cpp
  new sorting algo
  sample
  soilmoisture_dataset.csv
  test.cpp
  to-do-something-related-to-shifting-user-modes-in-realtime
Labels: enhancement

#45 Create KMP.cpp
  Strings/KMP.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#47 Create rabin_karp.cpp
  Strings/rabin_karp.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#48 Create aho_corasick.cpp
  Strings/aho_corasick.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#50 Create binary_search.cpp
  Other/binary_search.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#51 Create floyd_cycle_detection.cpp
  Other/floyd_cycle_detection.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#52 Create hash_search.cpp
  Other/hash_search.cpp
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#53 Create interpolation_Search.cpp
  Other/interpolation_Search.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#54 Create median_Search.cpp
  Other/median_Search.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
